### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by JobDestroyer** [ProjectHoot/hoot-mobile#105]
Add an app icon

**Comment by MrNobodyX3** [comment]
Icons for app icon and a versatile version

![3F47AA3E-B734-4549-8358-7BFA58745118](https://user-images.githubusercontent.com/39644589/134035174-09c1c6e1-b0b5-4c6a-8aff-6e2dbe4ae767.png)
![15688BBC-14B1-4262-9B4A-C166760D2A1C](https://user-images.githubusercontent.com/39644589/134035178-f080b2d1-ec3a-4f17-b10e-8bc48c27aeb9.png)
![6CD020C5-5690-41EE-893B-B67434561F4B](https://user-images.githubusercontent.com/39644589/134035179-7b5bf8ad-03fd-4109-a038-82728c4a8c93.png)
![48F635CF-9D4A-4CF6-A68D-174B674BFBE1](https://user-images.githubusercontent.com/39644589/134035182-e1ab6755-bdae-4a4c-a9af-3ee1faaabc47.png)

**Comment by BrandonDyer64** [comment]
The art team needs to create a logo first.
