### ISSUE TITLE
New Community page placeholder text is invisible in app

### ISSUE THREAD

**Issue by eunjibyte** [ProjectHoot/hoot-mobile#179]
### Steps to reproduce
1. Tap Profile tab.
2. Click the Create a Community button. In dark mode, both the background and the Community Name field placeholder text are black.
3. Enter a community name of 4+ characters. In dark mode, both the background and the Description (Optional) field placeholder text are black.

**Comment by BrandonDyer64** [comment]
Do you mind elaborating a bit on this? A screenshot may also help

**Comment by ibukinoyoukai** [comment]
Elaborated above on this bug.

**Comment by BrandonDyer64** [comment]
Confirmed

Replicated on Android
