### ISSUE TITLE
More HTML tag support

### ISSUE THREAD

**Issue by BrandonDyer64** [ProjectHoot/hoot-mobile#183]
As noted in #160, there are many HTML tags that don't renter properly.

**Comment by ibukinoyoukai** [comment]
Sensible HTML5 tags that don't render properly in the app include:

- Horizontal rule: `<hr>`
- Quote text: `<blockquote>`
- Marked text: `<mark>`
- Small text: `<small>`
- Deleted text: `<del>`
- Inserted text: `<ins>`
- Subscript: `<sub>`
- Superscript: `<sup>`
- Tables: `<table>`, `<caption>`, `<colgroup>`, `<col>`, `<tr>`, `<td>`, `<th>`
- Spoilers: `<details>`, `<summary>`

**Comment by BrandonDyer64** [comment]
Table support might need to be its own issue
