### ISSUE TITLE
User bios with many lines make the input field invisible

### ISSUE THREAD

**Issue by eunjibyte** [ProjectHoot/hoot-mobile#248]
### Steps to reproduce
1.While logged in, tap the profile tab in the Play app.
2. Tap the pencil icon.
3. Tap the User bio field, type a character in, then tap return 42+ times. The input field should unexpectedly turn invisible.

**Comment by BrandonDyer64** [comment]
The user edit form is currently unimplemented

**Comment by BrandonDyer64** [comment]
Closing as duplicate of #197
